#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Registrar o Auto Loader
|--------------------------------------------------------------------------
|
| O Composer fornece um carregador de classes automaticamente gerado
| para nossa aplicação. Só precisamos utilizá-lo! Vamos requerê-lo
| neste script para que não precisemos nos preocupar com o
| carregamento manual de nossas classes. É ótimo poder relaxar.
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Executar a Aplicação Artisan
|--------------------------------------------------------------------------
|
| Ao executar a aplicação de console, o comando CLI atual será
| executado neste console e a resposta enviada de volta ao terminal
| ou outro dispositivo de saída para os desenvolvedores. Aqui vamos nós!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Encerrar a Aplicação
|--------------------------------------------------------------------------
|
| Uma vez que o Artisan tenha terminado de executar, dispararemos os eventos
| de encerramento para que qualquer trabalho final possa ser realizado pela
| aplicação antes de encerrarmos o processo. Esta é a última coisa a acontecer
| na requisição.
|
*/

$kernel->terminate($input, $status);

exit($status);
